version: '3.8'

services:
  listinggenius:
    image: justincnn/listinggenius:latest
    container_name: listinggenius_app
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - listinggenius_data:/app/database
    env_file:
      - .env

volumes:
  listinggenius_data:
